version: '3.1'
services:
  probation-teams:
    image: quay.io/hmpps/probation-caselist-sampler:latest
    networks:
      - hmpps
    container_name: probation-caselist-sampler
    depends_on:
      - nomis-oauth2-server
    ports:
      - '8085:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health/ping']
    environment:
      - SERVER_PORT=8080
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_PASSWORD=admin_password
      - SPRING_PROFILES_ACTIVE=stdout

  nomis-oauth2-server:
    image: quay.io/hmpps/nomis-oauth2-server:latest
    networks:
      - hmpps
    container_name: nomis-oauth2-server
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  hmpps:
