spring:
  profiles:
    include: stdout

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

graceful:
  shutdown:
    enabled: false
